### ISSUE TITLE
Doesn't work MoveToRegion in my ViewModel

### ISSUE THREAD

**Issue by andresgutice** [nuitsjp/Xamarin.Forms.GoogleMaps.Bindings#7] opened 2017-07-22 14:20 UTC
Hi there, my problem is i can't move the map from my viewmodel, i followed the sample and i've tried this:

1) In the Xaml of the project, i added this Behavior in my GoogleMap:
`<bindings:MoveToRegionBehavior Request="{Binding Request}"/>`

2) In the ViewModel i added this request:
`public MoveToRegionRequest Request { get; } = new MoveToRegionRequest();`

3) and later, in the same ViewModel, i created a method that is in the construct of the ViewModel, this has the next line of code:
`Request.MoveToRegion( 
                MapSpan.FromCenterAndRadius(
                    new Position(35.681298, 139.766247), 
                    Distance.FromKilometers(2)));`

I guess that with this one my map can move to region but nothing happens, of course in my page i've called the behaviors and my ViewModel, what am I doing wrong?

Sorry for my English :)

**Comment by nuitsjp** [comment] 2017-08-12 08:11
I'm sorry for the late reply.
In the View Model constructor, the Request is not yet bound to the Behavior.
For example, please execute after Page Appling event.

**Comment by nuitsjp** [comment] 2017-08-13 03:15
If this is not possible, provide a code sample that will work.

**Comment by valentasm1** [comment] 2017-08-30 22:31
Have you tried one from example?
`MoveCameraRequest.MoveCamera(CameraUpdateFactory.NewCameraPosition(
                new CameraPosition(
                    new Position(35.681298, 139.766247), // Tokyo
                    17d, // zoom
                    45d, // bearing(rotation)
                    60d // tilt
                ))); ;`

**Comment by nuitsjp** [comment] 2017-09-02 06:58
Of course. Did you have any problems?

**Comment by valentasm1** [comment] 2017-09-02 13:42
I think you have this one related problem https://forums.xamarin.com/discussion/25537/android-googlemap-resets-camera-to-rome . I am not sure if it could help you but some workaround `Device.StartTimer(TimeSpan.FromMilliseconds(500), () =>
{
	MoveCameraRequest.MoveCamera(
		CameraUpdateFactory.NewCameraPosition(
			new CameraPosition(
				new Position(arg.Latitude, arg.Longitude),
				17d //Zoom
			)));
	return false;
});`
If you find better solution let me know. Also if you trigger location change from command it works well for me, just when starting map it does not work.

**Comment by nuitsjp** [comment] 2017-09-04 00:36
On the former problem:
I knew for the first time. I will investigate, but I think it will take time.

About the latter:
Is it executed with the ViewModel's constructor?
in that case…
In view of the mechanism, the InitializeComponent of the View must be completed before it works.
Please try using the page's Appearing Event etc.

**Comment by nuitsjp** [comment] 2018-06-06 14:59
Close it because it does not reproduce.

**Closed as completed by nuitsjp** 2018-06-06 14:59 UTC
