### ISSUE TITLE
load pin at the start

### ISSUE THREAD

**Issue by angelru** [nuitsjp/Xamarin.Forms.GoogleMaps.Bindings#17] opened 2018-10-23 19:50 UTC
Hello,

I'm trying show pins at start with property Pins, however it does not work.

any solution? any example, please?

**Comment by nuitsjp** [comment] 2018-10-30 04:32
Please release the reproduction code to Github and others.
Check the code and send PR if there is a problem with the production code.

**Comment by angelru** [comment] 2019-01-23 13:08
@nuitsjp the issue is, that not load pins at start google maps. Only with MapClickedEventArgs.

Can you check it?

**Comment by nuitsjp** [comment] 2019-01-30 02:20
Sorry, I can not have much time now.
I will reply by checking once and collecting it by 15th.

**Comment by sglogowski** [comment] 2019-02-03 22:15
Hello guys, I have similar problem with pins bindings. When pins collection is initialized in ctor like this:

        public ObservableCollection<Pin> Pins { get; set; } = new ObservableCollection<Pin>();
        public MapPageModel()
        {
            Pins.Add(new Pin()
            {
                Position = new Position(11.1, 22.22),
                Label = "test",
                Icon = BitmapDescriptorFactory.DefaultMarker(Color.Red)
            });
        }

And in xaml I will set up maps like this:

            <maps:Map x:Name="TheMap"
                      MapType="Street" 
                      VerticalOptions="FillAndExpand" 
                      HorizontalOptions="FillAndExpand"
                      IsShowingUser="true">
                <maps:Map.Behaviors>
                    <bindings:BindingPinsBehavior Value="{Binding Pins}" />
                </maps:Map.Behaviors>
            </maps:Map>

Pins will not be displlayed on map. I discovered that in debugmode when adding new pins by "clicking on the map" the pins collection is empty. I think that `BindingPinsBehavior` is overriding collections.

Maybe I am doing somethings wrong with initializations, I am not any expert in XamarinForms (If so, please give me advice how to do that correcly :).

PS: I am using FreshMVVM framework and as workaround I am initalizing pins values in ViewIsAppearing method :)).

**Comment by nuitsjp** [comment] 2021-06-18 21:53
Maps implementation, it is not possible to bind a List with values.

This library binds the list of pins held by the Map to the ViewModel side.
This is because the mechanism is to add or change the values there.
Your implementation is appropriate.

Therefore, I am closing this Issue.

**Closed as completed by nuitsjp** 2021-06-18 21:53 UTC
